---

include:
  - project: veepee/vptech/ci-cd/markdown-lint
    ref: 1-latest
    file: gitlab-ci.yml
  - project: veepee/vptech/ci-cd/semantic-release
    ref: 2-latest
    file: gitlab-ci.yml
  - project: veepee/vptech/ci-cd/shellcheck
    ref: 1-latest
    file: gitlab-ci.yml

.template: &build
  stage: build
  image: docker.registry.vptech.eu/vptech/debian:buster
  before_script:
    - apt-get update  -qq -y
    - apt-get install -qq -y apt-transport-https ca-certificates curl debootstrap kmod gnupg-agent procps software-properties-common sudo systemd tar
    - ln -s /usr/share/debootstrap/scripts/gutsy /usr/share/debootstrap/scripts/focal
    - curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
    - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
    - apt-get update  -qq -y
    - apt-get install -qq -y docker-ce docker-ce-cli containerd.io
    - env DOCKER_DRIVER=vfs dockerd &
  artifacts:
    expire_in: 1 day
    paths:
      - image
  tags:
    - dind
  variables:
    DOCKER_DRIVER: overlay

.template: &deploy
  stage: deploy
  image: docker.registry.vptech.eu/docker:latest
  before_script:
    - docker login -u "$DOCKER_PUBLIC_REGISTRY_USERNAME" -p "$DOCKER_PUBLIC_REGISTRY_PASSWORD"
    - docker load -i image/ubuntu-v18.04.tar
    - docker load -i image/ubuntu-v18.04-systemd.tar
    - docker load -i image/ubuntu-v20.04.tar
    - docker load -i image/ubuntu-v20.04-systemd.tar
  only:
    - main
    - master
  services:
    - name: docker.registry.vptech.eu/docker:dind
      alias: docker
  tags:
    - dind
  variables:
    DOCKER_DRIVER: overlay

stages:
  - lint
  - build
  - deploy
  - release

build:18.04:
  <<: *build
  script:
    - ./build.sh -d bionic -v
    - mkdir image
    - docker save ubuntu:bionic > image/ubuntu-v18.04.tar

build:18.04-systemd:
  <<: *build
  script:
    - ./build.sh -d bionic -e "systemd" -T "systemd" -v
    - mkdir image
    - docker save ubuntu:bionic-systemd > image/ubuntu-v18.04-systemd.tar

build:20.04:
  <<: *build
  script:
    - ./build.sh -d focal -v
    - mkdir image
    - docker save ubuntu:focal > image/ubuntu-v20.04.tar

build:20.04-systemd:
  <<: *build
  script:
    - ./build.sh -d focal -e "systemd" -T "systemd" -v
    - mkdir image
    - docker save ubuntu:focal-systemd > image/ubuntu-v20.04-systemd.tar

# https://hub.docker.com/u/vptech/
vptech:
  <<: *deploy
  script:
    - docker tag ubuntu:bionic          vptech/ubuntu:bionic
    - docker tag ubuntu:bionic          vptech/ubuntu:18.04
    - docker tag ubuntu:bionic-systemd  vptech/ubuntu:bionic-systemd
    - docker tag ubuntu:bionic-systemd  vptech/ubuntu:18.04-systemd
    - docker tag ubuntu:focal           vptech/ubuntu:focal
    - docker tag ubuntu:focal           vptech/ubuntu:20.04
    - docker tag ubuntu:focal-systemd   vptech/ubuntu:focal-systemd
    - docker tag ubuntu:focal-systemd   vptech/ubuntu:20.04-systemd
    - docker tag ubuntu:focal           vptech/ubuntu:latest
    - docker push --all-tags vptech/ubuntu
# EOF
